[package]
name = "timer"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { vercion = "~0.5", features = ["postgres", "runtime-tokio-rustls"] }
tokio = { version = "~1.9", features = ["full"] }
